### ISSUE TITLE
Check for the exists of `globalThis.caches` before using it

### ISSUE THREAD

**Issue by kwaa** [oom-components/mastodon-comments#2]
[`globalThis.caches` are only available in HTTPS](https://developer.mozilla.org/en-US/docs/Web/API/caches), which means that the component will fail to load when tested locally.

https://github.com/oom-components/mastodon-comments/blob/3273d82e862395e91660c1620c6db123316fa609/src/comments.js#L116

**Comment by oscarotero** [comment]
Thanks for raising this.
I have published v0.2.2 fixing this issue :)
